apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.28.0"
  values:
    global:
      tlsDisable: true
    server:
      replicas: 1
      dataStorage:
        enabled: true
        size: 1Gi
        storageClassName: longhorn
      auditStorage:
        enabled: true
        size: 1Gi
        storageClassName: longhorn
      ha:
        enabled: true
        replicas: 1
        raft:
          enabled: true
          config: |
            ui = true
            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = "true"
            }
            storage "raft" {
              path = "/vault/data"
            }
            disable_mlock = true
    ui:
      enabled: true
