apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myweather
resources:
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-sa.yaml
  - cloudflare-sa.yaml
  - backend-service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
