apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: myweather
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-secret # This is the k8s Secret that will be created
    creationPolicy: Owner
  data:
  - secretKey: GEMINI_API_KEY
    remoteRef:
      key: myweather/backend
      property: GEMINI_API_KEY
  - secretKey: REACT_APP_RAPIDAPI_KEY
    remoteRef:
      key: myweather/backend
      property: REACT_APP_RAPIDAPI_KEY
