apiVersion: v1
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiZDM4N2ZmZmYxYzBkNTZmNzEwOTUwMjRiODQ3MzQwYzciLCJUdW5uZWxTZWNyZXQiOiI3bXdXT3FZWjBxRkhnVWl0a0hRMktZTHlEaHhzMjhaekZaSTZTRlcrMXBBPSIsIlR1bm5lbElEIjoiN2ZkNGQ2MDYtNDQ2Zi00ZjYxLTg3YTItMjJjODA3ZGUxMDg2IiwiRW5kcG9pbnQiOiIifQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: myweather
