apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: myweather
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend # Assuming this SecretStore already exists and points to Vault
    kind: SecretStore
  target:
    name: tunnel-credentials # This is the k8s Secret that will be created
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        credentials.json: "{{ .credentials_json }}" # Map the Vault key to the Secret key
  data:
  - secretKey: credentials_json
    remoteRef:
      key: myweather/cloudflare
      property: credentials_json
