apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: myweather
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret" # Mount path of the KVv2 engine
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "myweather"
          serviceAccountRef:
            name: "myweather-backend-sa"
