apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myweather
resources:
  - ../../base/myweather/
  - namespace.yaml 
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - ingress.yaml
  - backend-externalsecret.yaml 
  - eso-secret-store.yaml
