apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    # IMPORTANT: Change this to a free IP range on your local network
    # that is outside of your router's DHCP range.
    - 192.168.2.240-192.168.2.250
