apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myweather
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: vault
      namespace: vault
    - name: external-secrets
      namespace: external-secrets

  path: ./apps/staging/myweather
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
